name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/
          scope: "@mx-js"
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Check code style
        run: npm run lint
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.5
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          workspace: "."
          publish_command: "npm"
          commit_pattern: "^build: release (\\S+)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
