name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Check code style
        run: npm run lint
      - name: Publish
        run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
